import Link from 'next/link'
import { notFound } from 'next/navigation'
import { loadSession } from '@/server/domain/analysis/agents/orchestrator'
import { ReportView } from '@/components/report/ReportView'
import { ReportTitle } from '@/components/report/ReportTitle'
import { DashboardShell } from '@/components/layout/DashboardShell'

export const dynamic = 'force-dynamic'
export const revalidate = 0

export default async function ReportPage(props: {
  params: Promise<{ sessionId: string }>
}) {
  const { sessionId } = await props.params
  const session = await loadSession(sessionId)
  if (!session) notFound()

  if (
    session.status !== 'done' ||
    !session.report ||
    !session.analyzer ||
    !session.decider
  ) {
    return (
      <DashboardShell>
        <section className="mx-auto flex min-h-[60vh] max-w-3xl flex-col items-center justify-center px-4 py-8">
          <div className="card max-w-md text-center">
            <p className="text-sm font-medium text-fg">
              Report not ready yet
            </p>
            <p className="mt-1 text-xs text-muted">
              Current status:{' '}
              <span className="text-accent-hi">{session.status}</span>
              {session.error && (
                <span className="mt-1 block text-danger">{session.error}</span>
              )}
            </p>
            <Link href="/" className="btn-ghost mt-4">
              Back to home
            </Link>
          </div>
        </section>
      </DashboardShell>
    )
  }

  return (
    <DashboardShell
      headerActions={
        <Link
          href="/"
          className="hidden btn-ghost md:inline-flex"
          aria-label="New analysis"
        >
          New analysis
        </Link>
      }
    >
      <main className="mx-auto flex max-w-6xl flex-col gap-6 px-4 py-6 sm:px-6 sm:py-8">
        <ReportTitle
          sessionId={sessionId}
          initialName={
            session.reportName ?? `Report ${sessionId.slice(0, 8)}`
          }
          createdAt={session.createdAt}
        />

        <ReportView
          report={session.report}
          analyzer={session.analyzer}
          decider={session.decider}
          disambiguator={session.disambiguator!}
        />

        <footer className="pt-6 pb-2 space-y-1.5 text-center text-[11px] text-muted-2">
          <p>Generated by a 4-agent Gemini pipeline · indicative values only</p>
          <p className="max-w-2xl mx-auto leading-relaxed">
            <span className="font-medium text-muted">Demo notice:</span> all figures are based on generic industry benchmarks and are for demonstration purposes only. Sector analysis performs a live lookup on available market data — values may change as underlying data is updated. This report does not constitute professional advice.
          </p>
        </footer>
      </main>
    </DashboardShell>
  )
}
